#!/bin/bash
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Mcherry_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Mcherry_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Mcherry_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Ime4_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Ime4_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Ime4_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Mcherry_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Mcherry_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Mcherry_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Ime4_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Ime4_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Ime4_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Ime4_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Ime4_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Ime4_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Mcherry_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Mcherry_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Mcherry_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Ime4_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Ime4_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Ime4_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Mcherry_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Mcherry_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Mcherry_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Mcherry_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Mcherry_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Mcherry_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Ime4_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Ime4_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Ime4_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Ime4_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Ime4_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Ime4_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Mcherry_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Mcherry_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Mcherry_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Mcherry_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Mcherry_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Mcherry_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Ime4_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Ime4_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Ime4_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Mcherry_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Mcherry_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Mcherry_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Ime4_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Ime4_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Ime4_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Mcherry_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Mcherry_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Mcherry_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Mcherry_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Mcherry_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Mcherry_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Ime4_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Ime4_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_Input_Ime4_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Mcherry_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Mcherry_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Positive_Mcherry_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Ime4_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Ime4_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Negative_Ime4_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Mcherry_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Mcherry_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_m6AIP_Positive_Mcherry_SYS_HS.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Ime4_SYS_control.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Ime4_SYS_control.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep1_m6AIP_Negative_Ime4_SYS_control.sort.dedup_metrics.txt
java -jar /home/vr/software/picard.jar MarkDuplicates I=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Ime4_SYS_HS.sort.bam O=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Ime4_SYS_HS.sort.dedup.bam M=/home/vr/data/BoniniLab/SynapticSystems_Antibody/Rep2_Input_Ime4_SYS_HS.sort.dedup_metrics.txt

